app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Testing the medium editor
Route::get('editor', ['middleware' => 'auth', function() {
	return view('test.editor');
}]);

// Zoho Verify
Route::get('zohoverify/zohoverify.html', function() {
    return '1443551183895';
});

// Images
Route::post('image/upload', 'ImageController@upload');
Route::post('image/delete', 'ImageController@delete');

// API
Route::post('api/comment/new', 'CommentController@store');
Route::get('api/comment/{id}/delete', 'CommentController@destroy');
Route::get('api/article/bump/{article}', 'ArticlesController@bump');
Route::get('api/article/unbump/{article}', 'ArticlesController@unbump');
Route::post('api/article/feature/toggle', 'ArticlesController@toggleFeature');
Route::post('api/user/{id}/update-notify', 'UserController@updateNotify');
Route::post('api/user/{id}/remove', 'UserController@destroy');

// Basic Pages
Route::get('/', 'HomeController@index');
Route::get('category/{id}', 'CategoriesController@index');
Route::get('tag/{tag}', 'TagsController@show');
Route::get('about', function() { return view('about'); });
Route::get('help', function() { return view('help'); });
Route::get('legal', function() { return view('legal'); });

// Send us a message
Route::post('contact/send', 'ContactController@send');

// Articles Resource, with a singular option
Route::resource('articles', 'ArticlesController');
Route::get('article/pending', 'ArticlesController@pending');
Route::get('article/{articles}', 'ArticlesController@show');
Route::get('article/{articles}/edit', 'ArticlesController@edit');
Route::get('article/{articles}/publish', 'ArticlesController@publish');
Route::post('article/{articles}/request', 'ArticlesController@sendRequest');
Route::post('article/{articles}/delete', 'ArticlesController@destroy');
Route::get('top-stories', 'ArticlesController@topStories');

// Management
Route::get('approve', 'ManagementController@index');
Route::get('manage-users', 'UserController@manage');
Route::post('manage-users/make-editor', 'UserController@makeEditor');
Route::post('manage-users/make-user', 'UserController@makeUser');
Route::post('manage-users/create-redirect', 'UserController@createRedirect');
Route::post('manage-users/update-redirect', 'UserController@updateRedirect');
Route::post('manage-users/remove-redirect', 'UserController@removeRedirect');

// Feature
Route::get('feature', 'FeatureController@index');
Route::get('feature/edit', 'FeatureController@edit');
Route::patch('feature/edit', 'FeatureController@update');
Route::delete('feature/edit', 'FeatureController@destroy');

// User Profile
Route::get('user/{user}', 'UserController@index');
Route::get('user/{user}/written', 'UserController@written');
Route::get('user/{user}/bumped', 'UserController@bumped');
Route::get('user/{user}/commented', 'UserController@commented');
Route::get('user/{user}/edit', 'UserController@edit');
Route::post('user/{user}/edit', 'UserController@update');
Route::get('user/{user}/delete', 'UserController@delete');

// User Settings
Route::get('settings', 'UserController@settings');

// Register Confirmation
Route::get('register/confirm', 'Auth\AuthController@wait');
Route::get('register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'Auth\AuthController@confirm'
]);

// Login / Register
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::post('register', 'Auth\AuthController@postRegister');
Route::get('login/cas', 'Auth\AuthController@getCasLogin');
Route::get('logout/cas', 'Auth\AuthController@getCasLogout');

// Password Reset
Route::get('forgot', 'Auth\PasswordController@getEmail');
Route::post('forgot', 'Auth\PasswordController@postEmail');
Route::get('reset', 'Auth\PasswordController@getEmail');
Route::post('reset', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

// Redirects
// Make sure this is the last route entry
Route::get('/{slug}', ['uses' => 'RedirectController@checkRedirect']);

app/Article.php
<?php namespace App;

use Auth;
use App\Article;
use Carbon\Carbon;
use Conner\Likeable\LikeableTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use AlgoliaSearch\Laravel\AlgoliaEloquentTrait;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Cviebrock\EloquentSluggable\SluggableInterface;

class Article extends Model implements SluggableInterface {

	use LikeableTrait, SluggableTrait, SoftDeletes, AlgoliaEloquentTrait;

	protected $fillable = 
	[
		'title',
		'overview',
		'example',
		'advice',
		'published',
		'featured',
		'user_id',
		'category_id'
	];

	protected $sluggable = array(
        'build_from' => 'title',
        'save_to'    => 'slug',
        'on_update'  => true
    );

    /**
     * Make sure these return as dates
     * @var array
     */
    protected $dates = ['deleted_at'];

	/**
	 * Attributes for Algolia Search
	 *
	 * @var  array
	 */
	public $algoliaSettings = [
        'attributesToIndex' => [
        	'username',
            'title',
            'overview',
            'example',
            'advice'
        ]
    ];

    public function getAlgoliaRecord()
    {
    	// Inject username into search record
        return array_merge($this->toArray(), [
            'username' => $this->user->name,
            'url'	=> '/article/' . $this->slug
        ]);
    }

    /**
     * User relationship
     * One user can have many articles
     */

	public function user()
	{
		return $this->belongsTo('App\User')->withTrashed();
	}

	/**
	 * Category relationship
	 * One category can have many articles
	 */

	public function category()
	{
		return $this->belongsTo('App\Category');
	}

	/**
	 * Tag relationship
	 * Tags and articles can have many of each other
	 */

	public function tags()
	{
		return $this->belongsToMany('App\Tag')->withTimestamps();
	}

	/**
	 * Comment relationship
	 * Articles can have many comments
	 */

	public function comments()
	{
		// Order the comments with most recent
		return $this->hasMany('App\Comment')->orderBy('created_at', 'DESC');
	}

	/**
	 * Get class for article if it's a draft
	 */
	public function getDraftClassAttribute()
	{
		if ( ! $this->published ) {
			return ' draft';
		}

		return '';
	}

	/**
	 * Get amount of comments this article has
	 */
	public function getCommentCountAttribute()
	{
		return $this->comments()->count();
	}

	/**
	 * Get the popularity count for the article
	 * Based on count of bumps and comments
	 */
	public function getPopularityAttribute()
	{
		return $this->comment_count + $this->likeCount;
	}

	/**
	 * Has this article been featured?
	 */
	public function getWasFeaturedAttribute()
	{
		return ( $this->featured_on !== '0000-00-00 00:00:00' );
	}

	/**
	 * Get all classes related to the feature status
	 */
	public function getFeatureClassesAttribute()
	{
		$classes = ['star'];

		if ( $this->wasFeatured ) {
			array_push( $classes, 'hasbeen');
		}

		if ( $this->featured ) {
			array_push( $classes, 'featured');
		} else {
			array_push( $classes, 'unfeatured');
		}

		return implode(' ', $classes);
	}

	/**
	 * Set this article as featured
	 */
	public function feature()
	{
		// set featured attribute
		$this->featured = true;

		// set the featured date
		$this->featured_on = Carbon::now();

		// save
		$this->save();
	}

	/**
	 * Set this article as unfeatured
	 */
	public function unFeature()
	{
		// set featured attribute
		$this->featured = false;

		// save
		$this->save();
	}

 	/**
 	 * Toggle the featured status on/off
 	 */
	public function toggleFeatured() {
		if ( $this->featured == true ) {
			$this->unfeature();
			return false;
		} else {
			$this->feature();
			return true;
		}
	}

	/**
	 * Query articles that are featured
	 */
	public function scopeFeatured( $query )
	{
		return $query->where('featured', true);
	}

	/**
	 * Query articles that have been featured before
	 */
	public function scopeWasFeatured( $query )
	{
		return $query->where('featured_on', '!=', '0000-00-00 00:00:00');
	}

	/**
	 * Get list of articles sorted by popularity
	 * Get the top 20 super bumped articles
	 */
	public static function getTopArticles()
	{
	    // return Article::published()->get()->sortByDesc( function( $model )
	    // {
	    //     return $model->popularity;
	    // });
	    return Article::superBumped()->take(20)->get();
	}

	/**
	 * Get the total number of likes on Trace
	 */
	public static function getTotalBumps()
	{
		return Article::published()->has('likes')->count();
	}

	/**
	 * Get property of super bumped status
	 */
	public function getSuperBumpedAttribute()
	{
		// This doesn't seem efficient...
		// Get the collection of super bumped articles
		$super_bumps = Article::superBumped()->take(20)->get();

		// Is this article in the super bumps collection?
		return $super_bumps->contains( $this );
	}

	/**
	 * Query articles that have been super-bumped
	 * And join in the likeable count if it's not 0
	 */
	public function scopeSuperBumped( $query )
	{
		return $query
			->published()
			->where('created_at', '>', Carbon::now()->subYear())
			->join('likeable_like_counters', function( $join ) {
				$join->on('articles.id', '=', 'likeable_like_counters.likable_id')
					->where('likeable_like_counters.count', '>', 0);
			})
			->select('likeable_like_counters.count as like_count', 'articles.*')
			->orderBy('like_count', 'desc')
			->orderBy('created_at', 'desc');
	}

	/**
	 * Query Articles commented on by a user
	 */
	public function scopeWhereCommented( $query, $user_id )
	{
		return $query->whereHas('comments', function( $q ) use ( $user_id ) {
			$q->where('user_id', $user_id);
		});
	}

	/**
	 * Collect all articles that have been commented on by a user
	 */
	public static function commented( $user_id )
	{
		return Article::published()->whereCommented( $user_id )
			->get()
			->sortByDesc( function( $article ) {
				return $article->comments()->first()->created_at;
			});
	}

	/**
	 * Get a string appropriate for count of others
	 */
	private function peopleString( $count )
	{
		return ( $count === 1 ) ? ' other' : ' others';
	}

	/**
	 * Get the count and string of 
	 * others that have bumped this article
	 */
	public function getOthersBumpedAttribute() {
		$count = $this->likeCount;

		$others = ( $this->liked() ) ? $count-1 : $count;

		return $others . $this->peopleString( $others );
	}

	/**
	 * Only get published articles - query scope
	 * @param  query $query
	 */
	public function scopePublished( $query )
	{
		$query
			->where('published', true)		// published
			->whereNull('deleted_at');		// not deleted
	}

	/**
	 * Only get unpublished articles
	 */
	public function scopeUnpublished( $query )
	{
		$query->where('published', false);
	}

	/**
	 * return list for $this->tag_list
	 * @return Array
	 */
	public function getTagListAttribute()
	{
		return $this->tags->lists('id')->all();
	}

	/**
	 * Simple return for the created_at
	 */
	public function getDateAttribute()
	{
		return $this->created_at;
	}

	/**
	 * Return a human-readable difference
	 * for the date attribute
	 */
	public function getDateDiffAttribute()
	{
		return $this->created_at->diffForHumans();
	}

}

resources/views/partials/articles/comment.blade.php
@extends('partials.userblock')

@section('user-block-header')
    @parent
@overwrite

@section('user-block-content')
    <p class="time">{{ $comment->updated_at->diffForHumans() }}</p>
    <div class="message">{{ $comment->message }}</div>
    @if ( $currentUser->can('moderate-comment') || $currentUser->id == $user->id )
        <a class="delete-comment" data-comment-id="{{ $comment->id }}" href="#">Delete</a>
    @endif
@overwrite

resources/views/partials/articles/comments.blade.php
<section class="comments" id="comments">
    @foreach ($article->comments as $comment)
        @include('partials.articles.comment', [
            'class' => $comment->commentClasses, 
            'currentUser'=> $user, 
            'user' => $comment->user, 
            'commentAnchor' => $comment->id
        ])
    @endforeach
</section>

resources/views/partials/articles/horizontalMedium.blade.php
<article class="article-preview horizontal-medium{{ $article->superBumped ? ' super-bumped' : '' }}">
    <div class="article-thumbnail hover-image">
        <img class="super" src="{{ asset('img/emoji/bump-super.svg') }}">
        <a class="mask" href="{{ url('article', $article->slug) }}">
            <img class="spacer" src="{{ asset('img/aspect-normal.gif') }}">
            <div class="background" style="background-image: url('{{ $article->photo }}');"></div>
            {{-- <span class="hover-info">{{ $article->likeCount }}</span> --}}
        </a>
    </div>
    <div class="details">
        <a href="{{ url('article', $article->slug) }}" class="title"><h2>{{ $article->title }}</h2></a>
        {!! str_limit( $article->overview) !!}
        <ul class="user-meta">
            <li class="user-name"><a href="{{ url('user', $article->user->slug) }}">{{ $article->user->name }}</a></li>
            <li class="time">{{ $article->date_diff }}</li>
            <li class="comments">
                <a href="{{ url('article', $article->slug) }}#comments">
                    {{ $article->comments->count() }} <span class="icon-comment"></span>
                </a>
            </li>
            <li class="bumps{{ $article->liked() ? ' bumped' : '' }}">
                {{ $article->likeCount }} <span class="icon-bump"></span>
            </li>
        </ul>
    </div>
</article>

resources/views/partials/articles/pagination.blade.php
@if ( $articles->lastPage() > 1 )
    <div class="pagination">
        <div class="previous">
            @if ( $articles->currentPage() > 1 )
                <a href="{{ $articles->previousPageUrl() }}">&larr; Previous page</a>
            @endif
        </div>
        
        <div class="page">
            {{ $articles->currentPage() }} of {{ $articles->lastPage() }}
        </div>

        <div class="next">
            @if ( $articles->hasMorePages() )
                <a href="{{ $articles->nextPageUrl() }}">Next page &rarr;</a>
            @endif
        </div>
    </div>
@endif

resources/views/partials/articles/verticalFeature.blade.php
<article class="article-preview vertical-feature{{ $article->superBumped ? ' super-bumped' : '' }}">
    <div class="details">
        <a href="{{ url('article', $article->slug) }}" class="title"><h2>{{ $article->title }}</h2></a>
    </div>

    <header>

        {{-- User Block --}}
        @include('partials.userblock', ['user' => $article->user])

    
        <ul class="user-meta">
            <li class="comments">
                <a href="{{ url('article', $article->slug) }}#comments">{{ $article->comments->count() }} <span class="icon-comment"></span></a>
            </li>
            <li class="bumps{{ $article->liked() ? ' bumped' : '' }}">{{ $article->likeCount }} <span class="icon-bump"></span></li>
        </ul>

    </header>

    <div class="article-thumbnail">
        <img class="super" src="{{ asset('img/emoji/bump-super.svg') }}">
        <a class="mask" href="{{ url('article', $article->slug) }}">
            <img class="spacer" src="{{ asset('img/aspect-wider.gif') }}">
            <div class="background" style="background-image: url('{{ $article->photo }}');"></div>
            <span class="hover-info">{{ $article->likeCount }}</span>
        </a>
    </div>
    <div class="overview">
        {!! str_limit( $article->overview, 100) !!}
    </div>
    <a href="{{ url('article', $article->slug)  }}" class="continue">Continue reading &rarr;</a>
</article>

<hr>

resources/views/partials/articles/verticalMedium.blade.php
<article class="article-preview vertical-medium{{ $article->superBumped ? ' super-bumped' : '' }}{{ $article->draftClass }}">
    <div class="article-thumbnail hover-image">
        <img class="super" src="{{ asset('img/emoji/bump-super.svg') }}">
        <a class="mask" href="{{ url('article', $article->slug) }}">
            <img class="spacer" src="{{ asset('img/aspect-wide.gif') }}">
            <div class="background" style="background-image: url('{{ $article->photo }}');"></div>
            @if ( $article->draftClass )
                <span class="draft-info">Under Review</span>
            @endif
        </a>
    </div>
    <div class="details">
        @if( Auth::user()->can('set-featured-content') )
            <div class="admin-control">
                <a href="#" class="star-control" data-id="{{ $article->id }}"><div class="{{ $article->featureClasses }}"><img src="{{ asset('img/aspect-square.gif') }}"></div></a>
            </div>
        @endif
        <a href="{{ url('article', $article->slug) }}" class="title"><h2>{{ $article->title }}</h2></a>
        <ul class="user-meta">
            <li class="user-name">
                @include('partials.user-link', ['user' => $article->user])
            </li>
            <li class="time">{{ $article->date_diff }}</li>
        </ul>
    </div>
</article>