app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Testing the medium editor
Route::get('editor', ['middleware' => 'auth', function() {
	return view('test.editor');
}]);

// Zoho Verify
Route::get('zohoverify/zohoverify.html', function() {
    return '1443551183895';
});

// Images
Route::post('image/upload', 'ImageController@upload');
Route::post('image/delete', 'ImageController@delete');

// API
Route::post('api/comment/new', 'CommentController@store');
Route::get('api/comment/{id}/delete', 'CommentController@destroy');
Route::get('api/article/bump/{article}', 'ArticlesController@bump');
Route::get('api/article/unbump/{article}', 'ArticlesController@unbump');
Route::post('api/article/feature/toggle', 'ArticlesController@toggleFeature');
Route::post('api/user/{id}/update-notify', 'UserController@updateNotify');
Route::post('api/user/{id}/remove', 'UserController@destroy');

// Basic Pages
Route::get('/', 'HomeController@index');
Route::get('category/{id}', 'CategoriesController@index');
Route::get('tag/{tag}', 'TagsController@show');
Route::get('about', function() { return view('about'); });
Route::get('help', function() { return view('help'); });
Route::get('legal', function() { return view('legal'); });

// Send us a message
Route::post('contact/send', 'ContactController@send');

// Articles Resource, with a singular option
Route::resource('articles', 'ArticlesController');
Route::get('article/pending', 'ArticlesController@pending');
Route::get('article/{articles}', 'ArticlesController@show');
Route::get('article/{articles}/edit', 'ArticlesController@edit');
Route::get('article/{articles}/publish', 'ArticlesController@publish');
Route::post('article/{articles}/request', 'ArticlesController@sendRequest');
Route::post('article/{articles}/delete', 'ArticlesController@destroy');
Route::get('top-stories', 'ArticlesController@topStories');

// Management
Route::get('approve', 'ManagementController@index');
Route::get('manage-users', 'UserController@manage');
Route::post('manage-users/make-editor', 'UserController@makeEditor');
Route::post('manage-users/make-user', 'UserController@makeUser');
Route::post('manage-users/create-redirect', 'UserController@createRedirect');
Route::post('manage-users/update-redirect', 'UserController@updateRedirect');
Route::post('manage-users/remove-redirect', 'UserController@removeRedirect');

// Feature
Route::get('feature', 'FeatureController@index');
Route::get('feature/edit', 'FeatureController@edit');
Route::patch('feature/edit', 'FeatureController@update');
Route::delete('feature/edit', 'FeatureController@destroy');

// User Profile
Route::get('user/{user}', 'UserController@index');
Route::get('user/{user}/written', 'UserController@written');
Route::get('user/{user}/bumped', 'UserController@bumped');
Route::get('user/{user}/commented', 'UserController@commented');
Route::get('user/{user}/edit', 'UserController@edit');
Route::post('user/{user}/edit', 'UserController@update');
Route::get('user/{user}/delete', 'UserController@delete');

// User Settings
Route::get('settings', 'UserController@settings');

// Register Confirmation
Route::get('register/confirm', 'Auth\AuthController@wait');
Route::get('register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'Auth\AuthController@confirm'
]);

// Login / Register
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::post('register', 'Auth\AuthController@postRegister');
Route::get('login/cas', 'Auth\AuthController@getCasLogin');
Route::get('logout/cas', 'Auth\AuthController@getCasLogout');

// Password Reset
Route::get('forgot', 'Auth\PasswordController@getEmail');
Route::post('forgot', 'Auth\PasswordController@postEmail');
Route::get('reset', 'Auth\PasswordController@getEmail');
Route::post('reset', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

// Redirects
// Make sure this is the last route entry
Route::get('/{slug}', ['uses' => 'RedirectController@checkRedirect']);

app/User.php
<?php namespace App;

use App\Article;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Auth\Passwords\CanResetPassword;
use AlgoliaSearch\Laravel\AlgoliaEloquentTrait;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract, SluggableInterface {

	use Authenticatable, CanResetPassword, EntrustUserTrait, SluggableTrait, SoftDeletes, AlgoliaEloquentTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * Settings for generated slug
	 */
	protected $sluggable = array(
        'build_from' => 'name',
        'on_update'  => true
    );

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'first_name', 
		'last_name',
		'scad_id',
		'email',
		'password',
		'avatar',
		'avatar_index',
		'avatar_default',
		'pro_title',
		'hometown',
		'major',
		'experience',
		'twitter',
		'instagram',
		'linkedin',
		'public_email',
		'facebook',
		'website',
		'custom_name'
	];

	/**
	 * Attributes for Algolia Search
	 *
	 * @var  array
	 */
	public $algoliaSettings = [
        'attributesToIndex' => [
            'name',
            'hometown'
        ]
    ];

    public function getAlgoliaRecord()
    {
    	// Inject name into search record
        return array_merge($this->toArray(), [
            'name' => $this->name,
            'url'	=> '/user/' . $this->slug
        ]);
    }

	/**
	 * Make sure these return as dates
	 * @var array
	 */
	protected $dates = ['deleted_at'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	/**
	 * Get the user's full name or custom name
	 */
	public function getNameAttribute()
	{
		return (!$this->custom_name) ? $this->first_name . ' ' . $this->last_name : $this->custom_name;
	}

	/**
	 * Extend the create function
	 */
	public static function create(array $attributes = [])
	{
		// add a random user profile image
		$index = str_pad( rand(1, 10) , 2, '0', STR_PAD_LEFT);
		$attributes['avatar_default'] = '/img/emoji/face-' . $index . '.svg';

		// manually set password for now
		$attributes['password'] = bcrypt('toothbrush');
		
		// run default create
		return parent::create( $attributes );
	}

	/**
	 * Get count of this user's articles
	 * that have been super bumped
	 */
	public function getSuperCountAttribute()
	{
		// Get the current list of super bumps
		$super_bumps = Article::with('user')->superBumped()->take(20)->get();

		// Get this users bumped articles
		$articles = $this->bumped->get();

		// How many are in the collection with this user's ID?
		return $super_bumps->where('user_id', $this->id)->count();
	}

	/**
	 * Get this user's articles
	 * 
	 * @return collection
	 */
	public function articles()
	{
		return $this->hasMany('App\Article')->whereNull('articles.deleted_at');
	}

	/**
	 * Get this user's comments
	 * 
	 * @return collection
	 */
	public function comments()
	{
		return $this->hasMany('App\Comment');
	}

	/**
	 * Get articles this user has commented on
	 * 
	 * @return collection
	 */
	public function getCommentedAttribute()
	{
		/*
			// Actual workign query:

			select articles.id, comments.message, comments.user_id from `articles` 
			inner join `comments` 
			on `articles`.`id` = `comments`.`article_id`
			and `comments`.`user_id` = 1
			where ( articles.id, comments.created_at ) in
			(
				select c.article_id, max(c.created_at)
				from comments c
				group by c.article_id
			)
			order by comments.created_at desc

		 */

		$user_id = $this->id;

		return Article::published()->join('comments', function( $join ) use ( $user_id ) {
			$join->on('articles.id', '=', 'comments.article_id')
				->where('comments.user_id', '=', $user_id);
		})
		->select('comments.id as comment_id', 'articles.*')
		->whereRaw('(`articles`.`id`, `comments`.`created_at`) in (select comments.article_id, max(comments.created_at) from `comments` group by `article_id`)')
		->orderBy('comments.created_at', 'desc');
	}

	/**
	 * Get the count of articles this user has commented on
	 */
	public function getCommentedCountAttribute()
	{
		return $this->commented->count();
	}

	/**
	 * Get articles this user has bumped
	 */
	public function getBumpedAttribute()
	{
		return Article::published()->whereLiked( $this->id );
	}

	/**
	 * Get number of articles this user has bumped
	 */
	public function getBumpedCountAttribute()
	{
		// instead use Article::published()->likeCount? 
		// maybe same thing
		return $this->bumped->count();
	}

	/**
	 * Make sure avatar returns something useful
	 */
	public function getAvatarImageAttribute()
	{
		if ( ! $this->avatar ) {
			return $this->avatar_default;
		}

		return $this->avatar;
	}

	/**
	 * Get the email notification setting status
	 */
	public function getNotificationStatusAttribute()
	{
		return $this->email_notify;
	}

	/**
	 * Query scope for finding user by SCAD ID
	 */
	public function scopeWhereScadId ( $query, $id )
	{
		return $query
			->where('scad_id', $id)
			->orWhere('scad_id', ltrim( $id, '0' ))
			->orWhere('scad_id', str_pad( $id, 9, '0', STR_PAD_LEFT ));
	}

	/**
	 * Accessor for finding by scad id
	 */
	public static function findByScadId ( $id )
	{
		return self::whereScadId( $id )->first();
	}

}

resources/views/user/bumped.blade.php
@extends('app')

@section('content')
    <div class="container article-results">
        <section class="not-sidebar">
            
            <h1 class="page-title">Bumped by <span class="stand-out">{{ $user->name }}</span></h1>

            @include('articles.list', ['listClass' => 'third'])
            
        </section>
    </div>
@endsection

resources/views/user/bye.blade.php
@extends('app')

@section('content')
    <div class="container thin user-settings">
        <h1 class="user-title"><span class="user">{{ $user->name }}: Settings:</span> Delete Account</h1>

        <section class="settings">            

            <div class="settings-block">
                <header>Delete Account</header>
                <main>
                    <p>You could have mistakenly arrived at this page. Or not.</p>
                    <p></p>
                    <p>We’ll be sad to see you go.</p>
                </main>
                <footer>
                    <ul class="wide">
                        <li><a href="#" id="confirm">Confirm</a></li>
                        <li><a href="{{ url('settings') }}" class="gray">Back</a></li>
                    </ul>
                </footer>
            </div>

            <div class="settings-block wave">
                <img src="{{ asset('img/emoji/wave.svg') }}">
            </div>
        </section>
    </div>
@stop

@section('page-js')
    <script type="text/javascript">
    $(function() {

        $('#confirm').click(function(e) {
            e.preventDefault();

            $.post(
                '/api/user/{{ $user->id }}/remove', 
                null, 
                function( response ) {
                    // They're gone, go home
                    window.location = '{{ url("/logout") }}';
                }
            );
        });

    });
    </script>
@endsection

resources/views/user/commented.blade.php
@extends('app')

@section('content')
    <div class="container article-results">
        <section class="not-sidebar">
            
            <h1 class="page-title">Commented by <span class="stand-out">{{ $user->name }}</span></h1>

            @include('articles.list', ['listClass' => 'third'])
            
        </section>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('app')

@section('content')
    <div class="container user-profile head-space editing">

        <section class="actions">
            <ul>
                <li><a href="#" class="button hollow gray" id="user-save">Save</a></li>
                <li><a href="{{ url('user', $user->slug) }}" class="button hollow gray">Cancel</a></li>
            </ul>
        </section>

        @include('errors.list')

        {!! Form::model($user, ['action' => ['UserController@edit', $user->slug], 'method' => 'post', 'id' => 'user-form', 'files' => true] ) !!}

        <section class="profile-header">
            <div class="avatar-wrap">
                <div class="photo">
                    @if ( $user->avatar )
                    <div class="avatar frame dropped" style="background-image:url('{{ $user->avatar }}');">
                    @else
                    <div class="avatar frame default" style="background-image:url('');">
                    @endif
                        <img class="default" src="{{ $user->avatar_default }}">
                        {!! Form::file('photo', ['accept' => 'image/png,image/jpeg,image/jpg,image/gif']) !!}
                        {!! Form::input('hidden', 'remove_avatar', null, ['id' => 'remove-avatar']) !!}
                    </div>
                </div>
                <div class="photo-edit">
                    <ul>
                        <li><a href="#" id="change-avatar">Change Your Face</a></li>
                        @if ( $user->avatar )
                            <li><a href="#" id="delete-avatar">Remove</a></li>
                        @else
                            <li><a href="#" id="delete-avatar" style="display:none;">Remove</a></li>
                        @endif
                    </ul>
                </div>
            </div>

            <div class="info no-pad">
                    <div class="info-group">
                        {{-- <h1 class="name">{{ $user->name }}</h1> --}}
                        {!! Form::input('text', 'name', null, array('class' => 'name form-control')) !!}
                        {!! Form::input('text', 'pro_title', null, array('placeholder' => 'Professional Title', 'class' => 'pro_title form-control')) !!}
                        {!! Form::input('hidden', 'user_id', $user->id) !!}
                    </div>

                    <div class="form-group info-group">
                        {{-- <label for="hometown">Hometown</label> --}}
                        {!! Form::label('hometown', 'Hometown') !!}
                        {!! Form::input('text', 'hometown', null, array('placeholder' => 'Where are you from? (eg, Houston, TX)', 'class' => 'form-control')) !!}
                    </div>

                    <div class="form-group info-group">
                        {!! Form::label('major', 'Major') !!}
                        {!! Form::input('text', 'major', null, array('placeholder' => 'What is your major? (eg, Painting)', 'class' => 'form-control')) !!}
                    </div>

                    <div class="form-group info-group">
                        {!! Form::label('experience', 'CLC Experience') !!}
                        {!! Form::input('text', 'experience', null, array('placeholder' => 'Brag about it here. (eg, client, quarter, etc.)', 'class' => 'form-control')) !!}
                    </div>
            </div>
        </section>

        <section class="social editable">
            <ul>
                <li>
                    <div class="popup{{ $user->linkedin ? ' filled' : '' }}">
                        {!! Form::label('linkedin', 'Linked In') !!}
                        <div class="url-field">
                            <span contenteditable="true" class="precede">linkedin.com/in/</span><span contenteditable="true" class="url" data-placeholder="username">{{ $user->linkedin }}</span>
                        </div>
                        {!! Form::input('hidden', 'linkedin') !!}
                    </div>
                    <a href="#"><span class="icon-linkedin"></span></a>
                </li>
                <li>
                    <div class="popup{{ $user->instagram ? ' filled' : '' }}">
                        {!! Form::label('instagram', 'Instagram') !!}
                        <div class="url-field">
                            <span contenteditable="true" class="precede">instagram.com/</span><span contenteditable="true" class="url" data-placeholder="username">{{ $user->instagram }}</span>
                        </div>
                        {!! Form::input('hidden', 'instagram') !!}
                    </div>
                    <a href="#"><span class="icon-instagram"></span></a>
                </li>
                <li>
                    <div class="popup{{ $user->twitter ? ' filled' : '' }}">
                        {!! Form::label('twitter', 'Twitter') !!}
                        <div class="url-field">
                            <span contenteditable="true" class="precede">twitter.com/</span><span contenteditable="true" class="url" data-placeholder="username">{{ $user->twitter }}</span>
                        </div>
                        {!! Form::input('hidden', 'twitter') !!}
                    </div>
                    <a href="#"><span class="icon-twitter"></span></a>
                </li>
                <li>
                    <div class="popup{{ $user->facebook ? ' filled' : '' }}">
                        {!! Form::label('facebook', 'Facebook') !!}
                        <div class="url-field">
                            <span contenteditable="true" class="precede">facebook.com/</span><span contenteditable="true" class="url" data-placeholder="username">{{ $user->facebook }}</span>
                        </div>
                        {!! Form::input('hidden', 'facebook') !!}
                    </div>
                    <a href="#"><span class="icon-facebook"></span></a>
                </li>
                <li>
                    <div class="popup{{ $user->public_email ? ' filled' : '' }}">
                        {!! Form::label('public_email', 'Email') !!}
                        <div class="url-field">
                            <span contenteditable="true" class="precede"></span><span contenteditable="true" class="url" data-placeholder="Add your email">{{ $user->public_email }}</span>
                        </div>
                        {!! Form::input('hidden', 'public_email') !!}
                    </div>
                    <a href="#"><span class="icon-email"></span></a>
                </li>
                <li>
                    <div class="popup{{ $user->website ? ' filled' : '' }}">
                        {!! Form::label('website', 'Website') !!}
                        <div class="url-field">
                            <span contenteditable="true" class="precede">http://</span><span contenteditable="true" class="url" data-placeholder="coolwebsite.com">{{ $user->website }}</span>
                        </div>
                        {!! Form::input('hidden', 'website') !!}
                    </div>
                    <a href="#"><span class="icon-web"></span></a>
                </li>
            </ul>
        </section>

        {!! Form::close() !!}
        
    </div>
@endsection

@section('page-js')
    <script type="text/javascript">
    $(function() {

        // get the photo holder
        var holder = $('.avatar.frame');
        var fileInput = holder.find('input[type="file"]');

        // Save button
        $('#user-save').click(function(e) {
            e.preventDefault();

            $('#user-form').submit();
        });

        // Change Avatar Button
        $('#change-avatar').click(function(e) {
            e.preventDefault();

            fileInput.trigger('click');
        });

        // Change Avatar Button
        $('#delete-avatar').click(function(e) {
            e.preventDefault();

            // tell the server to remove any 
            // existing photo file when we submit
            $('#remove-avatar').val(true);

            // Clear the file input by replacing it
            fileInput.replaceWith( fileInput = fileInput.clone( true ) );

            // Remove any background image
            holder.attr('style', 'background-image:url("");');

            // Show the default avatar
            holder.addClass('default').removeClass('dropped');

            // hide the delete button (nothing to delete anymore)
            $(this).hide();
        });

        // Drop states
        holder.on('dragover', function() {
            holder.addClass('hover');
        }).on('dragleave', function() {
            holder.removeClass('hover');
        });

        // Handle Dropping image
        fileInput.on('change', function(e) {
            var file = e.target.files[0];
            
            // States if needed
            holder.removeClass('hover default');
            holder.addClass('dropped');
            // $('#remove-avatar').val('');
            
            // ABORT, not an image
            // Consider a new way of alerting
            if (this.accept && $.inArray(file.type, this.accept.split(/, ?/)) == -1) {
              return alert('File type not allowed.');
            }
            
            // load the image
            var reader = new FileReader(file);
            reader.readAsDataURL(file);

            reader.onload = function(e) {
              var data = e.target.result

              // Add it in
              holder.attr('style', 'background-image:url("'+data+'");');

              // Show the delete button
              $('#delete-avatar').show();
            };
        });

        // Social Media Edit
        // custom close event for popup
        $('.popup')
        .on('popup:endedit', function() {
            var popup = $(this);
            var input = popup.find('input');

            // blur the fake field
            popup.find('.url').blur();

            // change the input value to the editable span's content
            popup.find('input').val( popup.find('.url').html() );

            // update the icon
            popup.toggleClass('filled', (input.val() !== ''));
        })
        .on('popup:close', function() {
            // trigger the save just in case
            $(this).trigger('popup:endedit');

            // hide the popup
            $(this).removeClass('active');
        });

        $(document).on('click touchend', function() {
            $('.popup.active').trigger('popup:close');
        });

        $('.social .url-field').click(function() {
            $(this).children('.url').focus();
        }).keypress(function (e) {
            if (e.which == 13) {
                // trigger end edit
                $(this).closest('.popup').trigger('popup:endedit');
                return false;
            }
        });

        $('.social.editable a').click(function(e) {
            e.preventDefault();
            e.stopPropagation();

            $('.popup.active').trigger('popup:close');

            $(this).prev().addClass('active');
        });

        $('.social.editable .popup').on('click touchend',function(e) {
            e.stopPropagation();
        });

    });
    </script>
@endsection

resources/views/user/show.blade.php
@extends('app')

@section('content')
    <div class="container user-profile head-space">
        
        @if (Auth::user()->id == $user->id || Auth::user()->can('manage-users'))
            <section class="actions">
                <ul>
                    <li><a href="{{ action('UserController@edit', $user->slug) }}" class="button hollow gray">Edit Profile</a></li>
                </ul>
            </section>
        @endif

        <section class="profile-header">

            <div class="avatar-wrap">
                <div class="photo">
                    <div class="avatar frame{{ $user->avatar ? ' photo' : '' }}" style="background-image:url('{{ $user->avatar_image }}');"></div>
                </div>
                @if ( $user->superCount > 0 )
                    <div class="super-count">
                        <span>{{ $user->superCount }}</span>
                    </div>
                @endif
            </div>

            <div class="info">
                <div class="info-group">
                    <h1 class="name">{{ $user->name }}</h1>
                    @if ( $user->pro_title )
                        <h3 class="title">{{ $user->pro_title }}</h3>
                    @endif
                </div>

                <ul>
                    <li>
                        <span class="icon-location"></span>
                        <span>{{ $user->hometown != '' ? $user->hometown : 'Trace, USA' }}</span>
                    </li>
                    <li>
                        <span class="icon-education"></span>
                        <span>{{ $user->major != '' ? $user->major : 'Graduating Sometime!' }}</span>
                    </li>
                    <li>
                        <span class="icon-prize"></span>
                        <span>{{ $user->experience != '' ? $user->experience : 'CLC Experience?' }}</span>
                    </li>
                </ul>
            </div>
        </section>

        <section class="social">
            <ul>
                @if ( $user->linkedin )
                    <li><a href="http://linkedin.com/in/{{ $user->linkedin }}" target="_blank"><span class="icon-linkedin"></span></a></li>
                @endif
                @if ( $user->instagram )
                    <li><a href="http://instagram.com/{{ $user->instagram }}" target="_blank"><span class="icon-instagram"></span></a></li>
                @endif
                @if ( $user->twitter )
                    <li><a href="http://twitter.com/{{ $user->twitter }}" target="_blank"><span class="icon-twitter"></span></a></li>
                @endif
                @if ( $user->facebook )
                    <li><a href="http://facebook.com/{{ $user->facebook }}" target="_blank"><span class="icon-facebook"></span></a></li>
                @endif
                @if ( $user->public_email )
                    <li><a href="mailto:{{ $user->public_email }}" target="_blank"><span class="icon-email"></span></a></li>
                @endif
                @if ( $user->website )
                    <li><a href="http://{{ $user->website }}" target="_blank"><span class="icon-web"></span></a></li>
                @endif
            </ul>
        </section>

        <hr>

        {{-- @if ( Auth::user()->can('manage-users') && ! $user->hasRole('admin') )
            <p class="text-center"><a href="#" class="red cd-popup-trigger">Delete this user</a></p>
            <hr>
        @endif --}}

        <section class="stats">

            @include('user.stat', [
                'count' => $articles_written_count,
                'countString' => 'Published',
                'items' => $articles_written,
                'slug' => 'written'
            ])

            @include('user.stat', [
                'count' => $articles_bumped_count,
                'countString' => 'Bumped',
                'items' => $articles_bumped,
                'slug' => 'bumped'
            ])
            
            @include('user.stat', [
                'count' => $articles_commented_count,
                'countString' => 'Comments',
                'items' => $articles_commented,
                'slug' => 'commented'
            ])
        </section>
    </div>
@endsection

@section('page-end')
    @include('partials.modals.delete-user', $user)
@endsection

@section('page-js')
    <script type="text/javascript">
        $(function() {
            $('#delete-user').click(function(e) {
                e.preventDefault();

                $.post(
                    '/api/user/{{ $user->id }}/remove', 
                    null, 
                    function( response ) {
                        // They're gone, go home
                        window.location = '{{ url("/") }}';
                    }
                );
            });
        });
    </script>
@endsection

resources/views/user/stat.blade.php
<div class="stat">
    <div class="stat-number">
        <h2>{{ $count }}</h2>
        <span>{{ $countString }}</span>
    </div>

    <div class="articles">
        @forelse( $items as $item )
            @include('partials.articles.verticalMedium', ['article' => $item])
        @empty
            <p class="empty">Nothing to see here :(</p>
        @endforelse
    </div>

    @if ( $count > 3 )
        <div class="more">
            <a href="{{ url('user', [ $user->slug, $slug ]) }}">More</a>
        </div>
    @endif
</div>

resources/views/user/written.blade.php
@extends('app')

@section('content')
    <div class="container article-results">
        <section class="not-sidebar">
            
            <h1 class="page-title">Articles from <span class="stand-out">{{ $user->name }}</span></h1>

            @include('articles.list', ['listClass' => 'third'])
            
        </section>
    </div>
@endsection